services:
  camb-operator:
    image: ghcr.io/cambrianone/camb-operator:${IMAGE_TAG:-latest}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
    environment:
      AVS_URL: '${AVS_URL:-http://host.docker.internal:3000}'
      AVS_WS_URL: '${AVS_WS_URL:-ws://host.docker.internal:3001}'
      API_URL: '${API_URL:-https://api.devnet.solana.com}'
      API_WS_URL: '${API_URL:-wss://api.devnet.solana.com}'
      LOG_LEVEL: '${LOG_LEVEL}'
      VOTER_KEY: '${VOTER_KEY:-2GDtCNMYyB88uX5rf2wdVbhvJKVP9amvxBuN2Ui63RcRJ1Vo3bRvmEFi3b7x6SHZSCaXp8Hhkmtctx2YbSyMMo5b}'
      ADMIN_KEY: '${ADMIN_KEY:-HoUrbYiLYunf36pXzjsYcPEPKJFZx9cTiyov67kGgsHgUjmfSKYeN2o2NLuBRHZ1TENXs5dVrLK8wKzNs2FJjZH}'
      NCN_PUBLIC_KEY: '${NCN_PUBLIC_KEY:-7MVEpWJoSfNH6QjPWcmFMMPXM2cncKqZheGqBYDNeMcx}'
      VAULT_PUBLIC_KEY: '${VAULT_PUBLIC_KEY:-B6Boct6guxkz9Smth4aNLutkhLmwVkZXXhHhp4ScrM68}'
      STORAGE_SPACE: '${STORAGE_SPACE:-75}'
      PROPOSAL_STORAGE_KEY: '${PROPOSAL_STORAGE_KEY:-demo}'

      OPERATOR_PUBLIC_KEY: '${OPERATOR_PUBLIC_KEY:-EyattRoNkPFjHKK6ZFFs6DmkH7XT41zpdGeMGNq9er59}'
      ORACLE_TYPE: '${ORACLE_TYPE:-container-stream}'
      ORACLE_ARGS: '${ORACLE_ARGS:-}'
      ORACLE_CONTAINER_IMAGE: '${ORACLE_CONTAINER_IMAGE:-oracle-update-current-date:latest}'
      
    extra_hosts:
      - "host.docker.internal:host-gateway"      
